theme: jekyll-theme-dinky
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
title: Delphi & Lazarus grid components
description: A few free grid components for Delphi & Lazarus.
social:
  name: Dmitry Morozov
  links:
    - https://www.facebook.com/profile.php?id=100004082021870
    - https://ru.linkedin.com/pub/dmitry-morozov/59/90a/794
    - https://github.com/dvmorozov 
